#pragma once

/*
* Generated by UEVRBridgeGen. Do not edit by hand.
* BlueprintGeneratedClass /Game/Mods/VRBody/Interfaces/_BI_VRWeapon._BI_VRWeapon_C
*/

#include "../SDK/Basic.hpp"
#include "Bridge.hpp"
#include "../SDK/CoreUObject_classes.hpp"
#include "../SDK/CoreUObject_structs.hpp"
#include "_ENUM_ItemCategory_structs.hpp"
#include "_ENUM_VRHand_structs.hpp"
#include "_ENUM_VRHandPose_structs.hpp"

namespace SDK
{
class A_BP_VRBody_C;
class USkeletalMeshComponent;

// BlueprintGeneratedClass /Game/Mods/VRBody/Interfaces/_BI_VRWeapon._BI_VRWeapon_C
class I_BI_VRWeapon_C final : public IInterface
{
public:
	static constexpr const wchar_t* BridgeClassPath = L"BlueprintGeneratedClass /Game/Mods/VRBody/Interfaces/_BI_VRWeapon._BI_VRWeapon_C";

	static bridge::ClassRef& BridgeClassRef()
	{
		static bridge::ClassRef Ref{ BridgeClassPath };
		return Ref;
	}
	static uevr::API::UClass* BridgeClass() { return BridgeClassRef().require(); }
	static class UClass* StaticClass() { return reinterpret_cast<class UClass*>(BridgeClass()); }
	static I_BI_VRWeapon_C* GetDefaultObj() { return reinterpret_cast<I_BI_VRWeapon_C*>(BridgeClass()->get_class_default_object()); }

	// Function UnloadWeapon (BlueprintCallable, BlueprintEvent)
	static bridge::Func& BridgeFunc_UnloadWeapon() { static bridge::Func Ref{ L"UnloadWeapon", {  } }; return Ref; }
	static void UnloadWeapon(uevr::API::UObject* BridgeTarget)
	{
		bridge::Call BridgeCall(BridgeFunc_UnloadWeapon(), BridgeTarget);
		BridgeCall.invoke();
	}

	// Function LoadWeapon (BlueprintCallable, BlueprintEvent)
	static bridge::Func& BridgeFunc_LoadWeapon() { static bridge::Func Ref{ L"LoadWeapon", {  } }; return Ref; }
	static void LoadWeapon(uevr::API::UObject* BridgeTarget)
	{
		bridge::Call BridgeCall(BridgeFunc_LoadWeapon(), BridgeTarget);
		BridgeCall.invoke();
	}

	// Function InitInteractionSources (BlueprintCallable, BlueprintEvent)
	static bridge::Func& BridgeFunc_InitInteractionSources() { static bridge::Func Ref{ L"InitInteractionSources", { L"InVRBody" } }; return Ref; }
	static void InitInteractionSources(uevr::API::UObject* BridgeTarget, class A_BP_VRBody_C* InVRBody)
	{
		bridge::Call BridgeCall(BridgeFunc_InitInteractionSources(), BridgeTarget);
		BridgeCall.set<class A_BP_VRBody_C*>(0, InVRBody);
		BridgeCall.invoke();
	}

	// Function GetDefaultParams (BlueprintCallable, BlueprintEvent)
	static bridge::Func& BridgeFunc_GetDefaultParams() { static bridge::Func Ref{ L"GetDefaultParams", { L"OutAttachSocketName", L"OutGripHandPose", L"OutWeaponOffset", L"OutUseHackerPawnWeaponAnims", L"OutEnabledLaserPointer", L"OutHand", L"OutIsHandheldConsumable", L"OutIsHandheldExplosive", L"OutItemCategory" } }; return Ref; }
	static void GetDefaultParams(uevr::API::UObject* BridgeTarget, class FName* OutAttachSocketName, E_ENUM_VRHandPose* OutGripHandPose, struct FTransform* OutWeaponOffset, bool* OutUseHackerPawnWeaponAnims, bool* OutEnabledLaserPointer, E_ENUM_VRHand* OutHand, bool* OutIsHandheldConsumable, bool* OutIsHandheldExplosive, E_ENUM_ItemCategory* OutItemCategory)
	{
		bridge::Call BridgeCall(BridgeFunc_GetDefaultParams(), BridgeTarget);
		if (OutAttachSocketName != nullptr) { BridgeCall.set<class FName>(0, *OutAttachSocketName); }
		if (OutGripHandPose != nullptr) { BridgeCall.set<E_ENUM_VRHandPose>(1, *OutGripHandPose); }
		if (OutWeaponOffset != nullptr) { BridgeCall.set<struct FTransform>(2, *OutWeaponOffset); }
		if (OutUseHackerPawnWeaponAnims != nullptr) { BridgeCall.set_bool(3, *OutUseHackerPawnWeaponAnims); }
		if (OutEnabledLaserPointer != nullptr) { BridgeCall.set_bool(4, *OutEnabledLaserPointer); }
		if (OutHand != nullptr) { BridgeCall.set<E_ENUM_VRHand>(5, *OutHand); }
		if (OutIsHandheldConsumable != nullptr) { BridgeCall.set_bool(6, *OutIsHandheldConsumable); }
		if (OutIsHandheldExplosive != nullptr) { BridgeCall.set_bool(7, *OutIsHandheldExplosive); }
		if (OutItemCategory != nullptr) { BridgeCall.set<E_ENUM_ItemCategory>(8, *OutItemCategory); }
		BridgeCall.invoke();
		if (OutAttachSocketName != nullptr) { *OutAttachSocketName = BridgeCall.get<class FName>(0); }
		if (OutGripHandPose != nullptr) { *OutGripHandPose = BridgeCall.get<E_ENUM_VRHandPose>(1); }
		if (OutWeaponOffset != nullptr) { *OutWeaponOffset = BridgeCall.get<struct FTransform>(2); }
		if (OutUseHackerPawnWeaponAnims != nullptr) { *OutUseHackerPawnWeaponAnims = BridgeCall.get_bool(3); }
		if (OutEnabledLaserPointer != nullptr) { *OutEnabledLaserPointer = BridgeCall.get_bool(4); }
		if (OutHand != nullptr) { *OutHand = BridgeCall.get<E_ENUM_VRHand>(5); }
		if (OutIsHandheldConsumable != nullptr) { *OutIsHandheldConsumable = BridgeCall.get_bool(6); }
		if (OutIsHandheldExplosive != nullptr) { *OutIsHandheldExplosive = BridgeCall.get_bool(7); }
		if (OutItemCategory != nullptr) { *OutItemCategory = BridgeCall.get<E_ENUM_ItemCategory>(8); }
	}

	// Function UseSourceMesh (BlueprintCallable, BlueprintEvent)
	static bridge::Func& BridgeFunc_UseSourceMesh() { static bridge::Func Ref{ L"UseSourceMesh", { L"Value" } }; return Ref; }
	static void UseSourceMesh(uevr::API::UObject* BridgeTarget, bool Value)
	{
		bridge::Call BridgeCall(BridgeFunc_UseSourceMesh(), BridgeTarget);
		BridgeCall.set_bool(0, Value);
		BridgeCall.invoke();
	}

	// Function SetSourceMesh (BlueprintCallable, BlueprintEvent)
	static bridge::Func& BridgeFunc_SetSourceMesh() { static bridge::Func Ref{ L"SetSourceMesh", { L"SourceMesh" } }; return Ref; }
	static void SetSourceMesh(uevr::API::UObject* BridgeTarget, class USkeletalMeshComponent* SourceMesh)
	{
		bridge::Call BridgeCall(BridgeFunc_SetSourceMesh(), BridgeTarget);
		BridgeCall.set<class USkeletalMeshComponent*>(0, SourceMesh);
		BridgeCall.invoke();
	}

	// Resolves the class and every property and function above, so no first use pays
	// the lookup mid-game. Returns false when the class is not loaded yet or a name did
	// not resolve; whatever is missing resolves on first use as usual.
	static bool BridgeWarmup()
	{
		uevr::API::UClass* Cls = BridgeClassRef().get();
		if (Cls == nullptr) { bridge::warm_skipped(BridgeClassPath); return false; }
		bool Ok = true;
		return Ok;
	}
};

}
