#pragma once

/*
* Generated by UEVRBridgeGen. Do not edit by hand.
* UserDefinedEnum /Game/Mods/VRBody/Enums/_ENUM_VRHand._ENUM_VRHand
*/

#include "../SDK/Basic.hpp"
#include "Bridge.hpp"

namespace SDK
{
// UserDefinedEnum /Game/Mods/VRBody/Enums/_ENUM_VRHand._ENUM_VRHand
enum class E_ENUM_VRHand : uint8
{
	Left = 0,
	Right = 1,
	E_ENUM_VRHand_MAX = 2,

	// Internal enumerator names, as Dumper-7 spells them.
	NewEnumerator0 = 0,
	NewEnumerator1 = 1,
};

}
