#pragma once

typedef enum ModEvent {
    MOD_EVENT_VR_HUD_HIDE_DASHBOARDS,
    MOD_EVENT_VR_HUD_INITIALIZE,
    MOD_EVENT_SHOW_MFD,
    MOD_EVENT_SHOW_IN_GAME_MENU,
    MOD_EVENT_MOUSE_ACTIVE,
} ModEvent;
