#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANIMBP_CyberStinger

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "ENUM_DeathBlowType_structs.hpp"
#include "ENUM_Emotions_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ANIMBP_CyberStinger.ANIMBP_CyberStinger_C
// 0x04F0 (0x07B0 - 0x02C0)
class UANIMBP_CyberStinger_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x02F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x0320(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x0348(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x0370(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x0398(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x03C0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x03E8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x0468(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x0498(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x0518(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0548(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x05C8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x05F8(0x0080)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x0678(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x06A8(0x00B0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0758(0x0048)()
	bool                                          Flying;                                            // 0x07A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void SetVoiceAmplitude(float VoiceAmplitude, bool* Result);
	void IsStunned(bool* Result);
	void SetStunnedSequence(class UAnimSequence* StunnedSequence, bool* Result);
	void SetSprintEnabled(bool SprintEnabled, bool* Result);
	void SetTravelMode(bool TravelModeOn, bool* Result);
	void GetAimTarget(class UOBJ_EnemyTarget_C** Target);
	void SetLookAtLocation(const struct FVector& Location, bool* Result);
	void SetLookAtAlpha(float Alpha, bool* Result);
	void SetMovementParameters(const struct FVector& Velocity, const struct FRotator& Rotation, const struct FRotator& DesiredRotation, bool* Result);
	void SetIsAlive(bool IsAlive, bool* Result);
	void ReceiveImpact(const struct FVector& Impulse, const struct FVector& ImpactLocation, const struct FVector& ImpactNormal, class FName BoneName, const class FString& DamageType, float DamageAmount, float FlinchTime, bool* Result);
	void ReceiveDeathBlow(ENUM_DeathBlowType BodyPart, bool* Result);
	void SetStandingTurn(float SignedAngleToTarget, bool IsStanding, bool* Result);
	void SetCatatonic(bool State, bool* Result);
	void SetStance(ENUM_Emotions Stance, bool* Result);
	void GetStance(ENUM_Emotions* Stance);
	void GetRotation(struct FRotator* AnimRotationPerSecond, float* AnimRotationAlpha);
	void SetRelativeAimAngleOffset(float YawOffset, float PitchOffset, float Alpha, bool* Result);
	void SetIdleOverrideSequence(class UAnimSequenceBase* IdleOverride, bool* Result);
	void GetIdleOverrideSequence(class UAnimSequenceBase** IdleOverride);
	void SetAimTarget(class UOBJ_EnemyTarget_C* Target, bool* Result);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ANIMBP_CyberStinger_AnimGraphNode_TransitionResult_CB84A574422E5BDA4D962E8B7C092030();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ANIMBP_CyberStinger_AnimGraphNode_TransitionResult_E5B8920E4093C31D425E449FE329D2D9();
	void ExecuteUbergraph_ANIMBP_CyberStinger(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ANIMBP_CyberStinger_C">();
	}
	static class UANIMBP_CyberStinger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UANIMBP_CyberStinger_C>();
	}
};
static_assert(alignof(UANIMBP_CyberStinger_C) == 0x000010, "Wrong alignment on UANIMBP_CyberStinger_C");
static_assert(sizeof(UANIMBP_CyberStinger_C) == 0x0007B0, "Wrong size on UANIMBP_CyberStinger_C");
static_assert(offsetof(UANIMBP_CyberStinger_C, UberGraphFrame) == 0x0002C0, "Member 'UANIMBP_CyberStinger_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_Root) == 0x0002C8, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_TransitionResult_5) == 0x0002F8, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_TransitionResult_4) == 0x000320, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_TransitionResult_3) == 0x000348, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_TransitionResult_2) == 0x000370, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_TransitionResult_1) == 0x000398, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_TransitionResult) == 0x0003C0, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_SequencePlayer_3) == 0x0003E8, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_StateResult_3) == 0x000468, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_SequencePlayer_2) == 0x000498, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_StateResult_2) == 0x000518, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_SequencePlayer_1) == 0x000548, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_StateResult_1) == 0x0005C8, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_SequencePlayer) == 0x0005F8, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_StateResult) == 0x000678, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_StateMachine) == 0x0006A8, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, AnimGraphNode_Slot) == 0x000758, "Member 'UANIMBP_CyberStinger_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UANIMBP_CyberStinger_C, Flying) == 0x0007A0, "Member 'UANIMBP_CyberStinger_C::Flying' has a wrong offset!");

}

