#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CYBER_PickupPedestal

#include "Basic.hpp"

#include "BP_CYBER_PickupPedestal_classes.hpp"
#include "BP_CYBER_PickupPedestal_parameters.hpp"


namespace SDK
{

// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.EVENT_OnDistanceTick
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_CYBER_PickupPedestal_C::EVENT_OnDistanceTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "EVENT_OnDistanceTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.EVENT_OnPickupTimeoutFinished
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_CYBER_PickupPedestal_C::EVENT_OnPickupTimeoutFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "EVENT_OnPickupTimeoutFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.TryGrantWeapon
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APAWN_Hacker_Simple_C*            HackerPawn                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CYBER_PickupPedestal_C::TryGrantWeapon(class APAWN_Hacker_Simple_C* HackerPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "TryGrantWeapon");

	Params::BP_CYBER_PickupPedestal_C_TryGrantWeapon Parms{};

	Parms.HackerPawn = HackerPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.SetWeaponPickupVisibility
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_CYBER_PickupPedestal_C::SetWeaponPickupVisibility(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "SetWeaponPickupVisibility");

	Params::BP_CYBER_PickupPedestal_C_SetWeaponPickupVisibility Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.UpdatePickupPedestal
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CYBER_PickupPedestal_C::UpdatePickupPedestal(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "UpdatePickupPedestal");

	Params::BP_CYBER_PickupPedestal_C_UpdatePickupPedestal Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.InitializePickupPedestal
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_CYBER_PickupPedestal_C::InitializePickupPedestal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "InitializePickupPedestal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_CYBER_PickupPedestal_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.BndEvt__BP_CYBER_PickupPedestal_OverlapVolume_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_CYBER_PickupPedestal_C::BndEvt__BP_CYBER_PickupPedestal_OverlapVolume_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "BndEvt__BP_CYBER_PickupPedestal_OverlapVolume_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_CYBER_PickupPedestal_C_BndEvt__BP_CYBER_PickupPedestal_OverlapVolume_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CYBER_PickupPedestal_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CYBER_PickupPedestal_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "ReceiveTick");

	Params::BP_CYBER_PickupPedestal_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CYBER_PickupPedestal_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "ReceiveEndPlay");

	Params::BP_CYBER_PickupPedestal_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CYBER_PickupPedestal.BP_CYBER_PickupPedestal_C.ExecuteUbergraph_BP_CYBER_PickupPedestal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CYBER_PickupPedestal_C::ExecuteUbergraph_BP_CYBER_PickupPedestal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CYBER_PickupPedestal_C", "ExecuteUbergraph_BP_CYBER_PickupPedestal");

	Params::BP_CYBER_PickupPedestal_C_ExecuteUbergraph_BP_CYBER_PickupPedestal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

