#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EXEC_CarpetPattern_QuarterLight

#include "Basic.hpp"

#include "INTERACT_BreakableSharedLightPanel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EXEC_CarpetPattern_QuarterLight.BP_EXEC_CarpetPattern_QuarterLight_C
// 0x0038 (0x0478 - 0x0440)
class ABP_EXEC_CarpetPattern_QuarterLight_C final : public AINTERACT_BreakableSharedLightPanel_C
{
public:
	class UStaticMeshComponent*                   LightGlass1;                                       // 0x0440(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BrokenGlass3;                                      // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BrokenGlass2;                                      // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BrokenGlass1;                                      // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BrokenGlass4;                                      // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        BrokenGlass;                                       // 0x0470(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EXEC_CarpetPattern_QuarterLight_C">();
	}
	static class ABP_EXEC_CarpetPattern_QuarterLight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EXEC_CarpetPattern_QuarterLight_C>();
	}
};
static_assert(alignof(ABP_EXEC_CarpetPattern_QuarterLight_C) == 0x000008, "Wrong alignment on ABP_EXEC_CarpetPattern_QuarterLight_C");
static_assert(sizeof(ABP_EXEC_CarpetPattern_QuarterLight_C) == 0x000478, "Wrong size on ABP_EXEC_CarpetPattern_QuarterLight_C");
static_assert(offsetof(ABP_EXEC_CarpetPattern_QuarterLight_C, LightGlass1) == 0x000440, "Member 'ABP_EXEC_CarpetPattern_QuarterLight_C::LightGlass1' has a wrong offset!");
static_assert(offsetof(ABP_EXEC_CarpetPattern_QuarterLight_C, SpotLight) == 0x000448, "Member 'ABP_EXEC_CarpetPattern_QuarterLight_C::SpotLight' has a wrong offset!");
static_assert(offsetof(ABP_EXEC_CarpetPattern_QuarterLight_C, BrokenGlass3) == 0x000450, "Member 'ABP_EXEC_CarpetPattern_QuarterLight_C::BrokenGlass3' has a wrong offset!");
static_assert(offsetof(ABP_EXEC_CarpetPattern_QuarterLight_C, BrokenGlass2) == 0x000458, "Member 'ABP_EXEC_CarpetPattern_QuarterLight_C::BrokenGlass2' has a wrong offset!");
static_assert(offsetof(ABP_EXEC_CarpetPattern_QuarterLight_C, BrokenGlass1) == 0x000460, "Member 'ABP_EXEC_CarpetPattern_QuarterLight_C::BrokenGlass1' has a wrong offset!");
static_assert(offsetof(ABP_EXEC_CarpetPattern_QuarterLight_C, BrokenGlass4) == 0x000468, "Member 'ABP_EXEC_CarpetPattern_QuarterLight_C::BrokenGlass4' has a wrong offset!");
static_assert(offsetof(ABP_EXEC_CarpetPattern_QuarterLight_C, BrokenGlass) == 0x000470, "Member 'ABP_EXEC_CarpetPattern_QuarterLight_C::BrokenGlass' has a wrong offset!");

}

