#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BROADCAST_Laptop_OfferOfEmployment

#include "Basic.hpp"

#include "BROADCAST_Base_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BROADCAST_Laptop_OfferOfEmployment.BROADCAST_Laptop_OfferOfEmployment_C
// 0x0058 (0x02F0 - 0x0298)
class UBROADCAST_Laptop_OfferOfEmployment_C final : public UBROADCAST_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       DeleteEmail;                                       // 0x02A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ScrollEmailAnim;                                   // 0x02A8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBorder*                                BORDER_DownloadProgress;                           // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IMAGE_TRIOP;                                       // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_HackingText;                                   // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_MessageDeleted;                                // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_No;                                            // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_Yes;                                           // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextTyper_C*                           TextTyper;                                         // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHacking;                                         // 0x02E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ScrollEmail();
	void StartHacking();
	void StartTypingDeleteResults();
	void PressDelete();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void ExecuteUbergraph_BROADCAST_Laptop_OfferOfEmployment(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BROADCAST_Laptop_OfferOfEmployment_C">();
	}
	static class UBROADCAST_Laptop_OfferOfEmployment_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBROADCAST_Laptop_OfferOfEmployment_C>();
	}
};
static_assert(alignof(UBROADCAST_Laptop_OfferOfEmployment_C) == 0x000008, "Wrong alignment on UBROADCAST_Laptop_OfferOfEmployment_C");
static_assert(sizeof(UBROADCAST_Laptop_OfferOfEmployment_C) == 0x0002F0, "Wrong size on UBROADCAST_Laptop_OfferOfEmployment_C");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, UberGraphFrame) == 0x000298, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, DeleteEmail) == 0x0002A0, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::DeleteEmail' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, ScrollEmailAnim) == 0x0002A8, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::ScrollEmailAnim' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, BORDER_DownloadProgress) == 0x0002B0, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::BORDER_DownloadProgress' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, IMAGE_TRIOP) == 0x0002B8, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::IMAGE_TRIOP' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, TXT_HackingText) == 0x0002C0, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::TXT_HackingText' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, TXT_MessageDeleted) == 0x0002C8, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::TXT_MessageDeleted' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, TXT_No) == 0x0002D0, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::TXT_No' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, TXT_Yes) == 0x0002D8, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::TXT_Yes' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, TextTyper) == 0x0002E0, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::TextTyper' has a wrong offset!");
static_assert(offsetof(UBROADCAST_Laptop_OfferOfEmployment_C, IsHacking) == 0x0002E8, "Member 'UBROADCAST_Laptop_OfferOfEmployment_C::IsHacking' has a wrong offset!");

}

