#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Citadel_EXT

#include "Basic.hpp"

#include "Citadel_EXT_classes.hpp"
#include "Citadel_EXT_parameters.hpp"


namespace SDK
{

// Function Citadel_EXT.Citadel_EXT_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACitadel_EXT_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Citadel_EXT_C", "ReceiveTick");

	Params::Citadel_EXT_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Citadel_EXT.Citadel_EXT_C.ExecuteUbergraph_Citadel_EXT
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACitadel_EXT_C::ExecuteUbergraph_Citadel_EXT(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Citadel_EXT_C", "ExecuteUbergraph_Citadel_EXT");

	Params::Citadel_EXT_C_ExecuteUbergraph_Citadel_EXT Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

