#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CyberspaceLifeSimulation

#include "Basic.hpp"

#include "SystemReShock_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CyberspaceLifeSimulation.CyberspaceLifeSimulation_C
// 0x0000 (0x01F0 - 0x01F0)
class UCyberspaceLifeSimulation_C final : public ULifeSimulation
{
public:
	bool OnActivateCell(const struct FVoxelWallLocation& WallLocation, class UPrimitiveComponent* PrimitiveComponent);
	bool OnDeactivateCell(const struct FVoxelWallLocation& WallLocation, class UPrimitiveComponent* PrimitiveComponent);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CyberspaceLifeSimulation_C">();
	}
	static class UCyberspaceLifeSimulation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCyberspaceLifeSimulation_C>();
	}
};
static_assert(alignof(UCyberspaceLifeSimulation_C) == 0x000008, "Wrong alignment on UCyberspaceLifeSimulation_C");
static_assert(sizeof(UCyberspaceLifeSimulation_C) == 0x0001F0, "Wrong size on UCyberspaceLifeSimulation_C");

}

