#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CYBR_Respawner

#include "Basic.hpp"

#include "CYBR_Respawner_classes.hpp"
#include "CYBR_Respawner_parameters.hpp"


namespace SDK
{

// Function CYBR_Respawner.CYBR_Respawner_C.CanSpawnOnWave
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   WaveNumber                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ACYBR_Respawner_C::CanSpawnOnWave(int32 WaveNumber, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "CanSpawnOnWave");

	Params::CYBR_Respawner_C_CanSpawnOnWave Parms{};

	Parms.WaveNumber = WaveNumber;

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function CYBR_Respawner.CYBR_Respawner_C.ResetSpawner
// (Public, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::ResetSpawner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "ResetSpawner");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.TryCreateSpawnOffsets
// (Protected, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::TryCreateSpawnOffsets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "TryCreateSpawnOffsets");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.TryInteract
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SourceActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              CursorPrimitive                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ENUM_InteractionType                    InteractionType                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSTRUCT_InteractResults          InteractResults                                        (Parm, OutParm, HasGetValueTypeHash)

void ACYBR_Respawner_C::TryInteract(class AActor* SourceActor, class UPrimitiveComponent* CursorPrimitive, ENUM_InteractionType InteractionType, struct FSTRUCT_InteractResults* InteractResults)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "TryInteract");

	Params::CYBR_Respawner_C_TryInteract Parms{};

	Parms.SourceActor = SourceActor;
	Parms.CursorPrimitive = CursorPrimitive;
	Parms.InteractionType = InteractionType;

	UObject::ProcessEvent(Func, &Parms);

	if (InteractResults != nullptr)
		*InteractResults = std::move(Parms.InteractResults);
}


// Function CYBR_Respawner.CYBR_Respawner_C.EVENT_OnRespawnedEnemyDied
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APAWN_SystemShockCharacter_C*     Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACYBR_Respawner_C::EVENT_OnRespawnedEnemyDied(class APAWN_SystemShockCharacter_C* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "EVENT_OnRespawnedEnemyDied");

	Params::CYBR_Respawner_C_EVENT_OnRespawnedEnemyDied Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CYBR_Respawner.CYBR_Respawner_C.OnSpawnEnemy
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::OnSpawnEnemy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "OnSpawnEnemy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.UpdateSpawnerSize
// (Protected, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::UpdateSpawnerSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "UpdateSpawnerSize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.UpdateSpawnTransitionOffset
// (Protected, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::UpdateSpawnTransitionOffset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "UpdateSpawnTransitionOffset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.UpdateSpawnerTransition
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACYBR_Respawner_C::UpdateSpawnerTransition(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "UpdateSpawnerTransition");

	Params::CYBR_Respawner_C_UpdateSpawnerTransition Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CYBR_Respawner.CYBR_Respawner_C.BeginPortalTransition
// (Protected, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::BeginPortalTransition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "BeginPortalTransition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.InitializeSpawner
// (Protected, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::InitializeSpawner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "InitializeSpawner");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.HasReachedRespawnLimit
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ACYBR_Respawner_C::HasReachedRespawnLimit(bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "HasReachedRespawnLimit");

	Params::CYBR_Respawner_C_HasReachedRespawnLimit Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function CYBR_Respawner.CYBR_Respawner_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ACYBR_Respawner_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CYBR_Respawner.CYBR_Respawner_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACYBR_Respawner_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "ReceiveTick");

	Params::CYBR_Respawner_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CYBR_Respawner.CYBR_Respawner_C.ExecuteUbergraph_CYBR_Respawner
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACYBR_Respawner_C::ExecuteUbergraph_CYBR_Respawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CYBR_Respawner_C", "ExecuteUbergraph_CYBR_Respawner");

	Params::CYBR_Respawner_C_ExecuteUbergraph_CYBR_Respawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

