#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DEBUG_Ghost

#include "Basic.hpp"

#include "WIDGET_DebugListItem_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DEBUG_Ghost.DEBUG_Ghost_C
// 0x0000 (0x0360 - 0x0360)
class UDEBUG_Ghost_C final : public UWIDGET_DebugListItem_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DEBUG_Ghost_C">();
	}
	static class UDEBUG_Ghost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDEBUG_Ghost_C>();
	}
};
static_assert(alignof(UDEBUG_Ghost_C) == 0x000008, "Wrong alignment on UDEBUG_Ghost_C");
static_assert(sizeof(UDEBUG_Ghost_C) == 0x000360, "Wrong size on UDEBUG_Ghost_C");

}

