#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X

#include "Basic.hpp"

#include "EMAIL_ITEM_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EMAIL_Taggert_Taggert_1_cyberspace_Turns-into_SHODAN_SHODAN-X.EMAIL_Taggert_Taggert_1_cyberspace_Turns-into_SHODAN_SHODAN-X_C
// 0x0000 (0x01A0 - 0x01A0)
class UEMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X_C final : public UEMAIL_ITEM_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EMAIL_Taggert_Taggert_1_cyberspace_Turns-into_SHODAN_SHODAN-X_C">();
	}
	static class UEMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X_C>();
	}
};
static_assert(alignof(UEMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X_C) == 0x000008, "Wrong alignment on UEMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X_C");
static_assert(sizeof(UEMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X_C) == 0x0001A0, "Wrong size on UEMAIL_Taggert_Taggert_1_cyberspace_Turns_into_SHODAN_SHODAN_X_C");

}

