#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ENUM_LadderMoveType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ENUM_LadderMoveType.ENUM_LadderMoveType
// NumValues: 0x0004
enum class ENUM_LadderMoveType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator3                           = 1,
	NewEnumerator2                           = 2,
	ENUM_MAX                                 = 3,
};

}

