#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ITEM_Recall

#include "Basic.hpp"

#include "ITEM_Software_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ITEM_Recall.ITEM_Recall_C
// 0x0000 (0x01E0 - 0x01E0)
class UITEM_Recall_C final : public UITEM_Software_Base_C
{
public:
	void Activate(class APAWN_SystemShockCharacter_C* Character, bool* Result);
	void CanActivate(class APAWN_SystemShockCharacter_C* Character, bool* Result);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ITEM_Recall_C">();
	}
	static class UITEM_Recall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UITEM_Recall_C>();
	}
};
static_assert(alignof(UITEM_Recall_C) == 0x000008, "Wrong alignment on UITEM_Recall_C");
static_assert(sizeof(UITEM_Recall_C) == 0x0001E0, "Wrong size on UITEM_Recall_C");

}

