#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PATCH_VisionEnhancement

#include "Basic.hpp"

#include "PATCH_VisionEnhancement_classes.hpp"
#include "PATCH_VisionEnhancement_parameters.hpp"


namespace SDK
{

// Function PATCH_VisionEnhancement.PATCH_VisionEnhancement_C.GetEffects
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             EffectsText                                            (Parm, OutParm)

void UPATCH_VisionEnhancement_C::GetEffects(class FText* EffectsText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PATCH_VisionEnhancement_C", "GetEffects");

	Params::PATCH_VisionEnhancement_C_GetEffects Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EffectsText != nullptr)
		*EffectsText = std::move(Parms.EffectsText);
}


// Function PATCH_VisionEnhancement.PATCH_VisionEnhancement_C.GetSideEffects
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             SideEffectsText                                        (Parm, OutParm)

void UPATCH_VisionEnhancement_C::GetSideEffects(class FText* SideEffectsText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PATCH_VisionEnhancement_C", "GetSideEffects");

	Params::PATCH_VisionEnhancement_C_GetSideEffects Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SideEffectsText != nullptr)
		*SideEffectsText = std::move(Parms.SideEffectsText);
}


// Function PATCH_VisionEnhancement.PATCH_VisionEnhancement_C.GetDuration
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             DurationText                                           (Parm, OutParm)

void UPATCH_VisionEnhancement_C::GetDuration(class FText* DurationText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PATCH_VisionEnhancement_C", "GetDuration");

	Params::PATCH_VisionEnhancement_C_GetDuration Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DurationText != nullptr)
		*DurationText = std::move(Parms.DurationText);
}


// Function PATCH_VisionEnhancement.PATCH_VisionEnhancement_C.UseConsumable
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APAWN_SystemShockCharacter_C*     Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UITEM_ConsumableBase_C*           ConsumedItem                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPATCH_VisionEnhancement_C::UseConsumable(class APAWN_SystemShockCharacter_C* Character, class UITEM_ConsumableBase_C** ConsumedItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PATCH_VisionEnhancement_C", "UseConsumable");

	Params::PATCH_VisionEnhancement_C_UseConsumable Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);

	if (ConsumedItem != nullptr)
		*ConsumedItem = Parms.ConsumedItem;
}

}

