#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PAWN_PlayerGhost

#include "Basic.hpp"

#include "PAWN_PlayerGhost_classes.hpp"
#include "PAWN_PlayerGhost_parameters.hpp"


namespace SDK
{

// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.RequestSkipSequence__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void APAWN_PlayerGhost_C::RequestSkipSequence__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "RequestSkipSequence__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.CancelSkipSequence__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void APAWN_PlayerGhost_C::CancelSkipSequence__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "CancelSkipSequence__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.ExecuteUbergraph_PAWN_PlayerGhost
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::ExecuteUbergraph_PAWN_PlayerGhost(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "ExecuteUbergraph_PAWN_PlayerGhost");

	Params::PAWN_PlayerGhost_C_ExecuteUbergraph_PAWN_PlayerGhost Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.ReceivePossessed
// (Event, Public, BlueprintEvent)
// Parameters:
// class AController*                      NewController                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::ReceivePossessed(class AController* NewController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "ReceivePossessed");

	Params::PAWN_PlayerGhost_C_ReceivePossessed Parms{};

	Parms.NewController = NewController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.ReceiveUnpossessed
// (Event, Public, BlueprintEvent)
// Parameters:
// class AController*                      OldController                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::ReceiveUnpossessed(class AController* OldController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "ReceiveUnpossessed");

	Params::PAWN_PlayerGhost_C_ReceiveUnpossessed Parms{};

	Parms.OldController = OldController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpAxisEvt_MenuNavAxis_Y_K2Node_InputAxisEvent_17
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpAxisEvt_MenuNavAxis_Y_K2Node_InputAxisEvent_17(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpAxisEvt_MenuNavAxis_Y_K2Node_InputAxisEvent_17");

	Params::PAWN_PlayerGhost_C_InpAxisEvt_MenuNavAxis_Y_K2Node_InputAxisEvent_17 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpAxisEvt_MenuNavAxis_X_K2Node_InputAxisEvent_16
// (BlueprintEvent)
// Parameters:
// float                                   AxisValue                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpAxisEvt_MenuNavAxis_X_K2Node_InputAxisEvent_16(float AxisValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpAxisEvt_MenuNavAxis_X_K2Node_InputAxisEvent_16");

	Params::PAWN_PlayerGhost_C_InpAxisEvt_MenuNavAxis_X_K2Node_InputAxisEvent_16 Parms{};

	Parms.AxisValue = AxisValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Down_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Down_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Down_K2Node_InputActionEvent_0");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Down_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Down_K2Node_InputActionEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Down_K2Node_InputActionEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Down_K2Node_InputActionEvent_1");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Down_K2Node_InputActionEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Up_K2Node_InputActionEvent_2
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Up_K2Node_InputActionEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Up_K2Node_InputActionEvent_2");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Up_K2Node_InputActionEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Up_K2Node_InputActionEvent_3
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Up_K2Node_InputActionEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Up_K2Node_InputActionEvent_3");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Up_K2Node_InputActionEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Right_K2Node_InputActionEvent_4
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Right_K2Node_InputActionEvent_4(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Right_K2Node_InputActionEvent_4");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Right_K2Node_InputActionEvent_4 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Right_K2Node_InputActionEvent_5
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Right_K2Node_InputActionEvent_5(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Right_K2Node_InputActionEvent_5");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Right_K2Node_InputActionEvent_5 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Left_K2Node_InputActionEvent_6
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Left_K2Node_InputActionEvent_6(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Left_K2Node_InputActionEvent_6");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Left_K2Node_InputActionEvent_6 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Left_K2Node_InputActionEvent_7
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Left_K2Node_InputActionEvent_7(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Left_K2Node_InputActionEvent_7");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Left_K2Node_InputActionEvent_7 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_8
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_8(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_8");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_8 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_9
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_9(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_9");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Alt2_K2Node_InputActionEvent_9 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_10
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_10(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_10");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_10 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_11
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_11(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_11");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Alt1_K2Node_InputActionEvent_11 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_RightThumbstick_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_RightThumbstick_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_RightThumbstick_K2Node_InputKeyEvent_0");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_RightThumbstick_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Home_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Home_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Home_K2Node_InputKeyEvent_1");

	Params::PAWN_PlayerGhost_C_InpActEvt_Home_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_12
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_12(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_12");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_12 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_13
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_13(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_13");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_Escape_K2Node_InputActionEvent_13 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_14
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_14(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_14");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_14 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_15
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_15(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_15");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Back_K2Node_InputActionEvent_15 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_16
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_16(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_16");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_16 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_17
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_17(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_17");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Accept_K2Node_InputActionEvent_17 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_18
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_18(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_18");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_18 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_19
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_19(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_19");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Accept_K2Node_InputActionEvent_19 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_20
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_20(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_20");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_20 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_21
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_21(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_21");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Alt1_K2Node_InputActionEvent_21 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_22
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_22(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_22");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_22 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_23
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_23(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_23");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_Alt2_K2Node_InputActionEvent_23 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_24
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_24(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_24");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_24 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_25
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_25(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_25");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_TabLeft_K2Node_InputActionEvent_25 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_26
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_26(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_26");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_26 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_27
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_27(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_27");

	Params::PAWN_PlayerGhost_C_InpActEvt_Gamepad_MenuNav_TabRight_K2Node_InputActionEvent_27 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Locked_Escape_K2Node_InputActionEvent_28
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Locked_Escape_K2Node_InputActionEvent_28(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Locked_Escape_K2Node_InputActionEvent_28");

	Params::PAWN_PlayerGhost_C_InpActEvt_Locked_Escape_K2Node_InputActionEvent_28 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_Locked_Escape_K2Node_InputActionEvent_29
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_Locked_Escape_K2Node_InputActionEvent_29(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_Locked_Escape_K2Node_InputActionEvent_29");

	Params::PAWN_PlayerGhost_C_InpActEvt_Locked_Escape_K2Node_InputActionEvent_29 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Back_K2Node_InputActionEvent_30
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Back_K2Node_InputActionEvent_30(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Back_K2Node_InputActionEvent_30");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Back_K2Node_InputActionEvent_30 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_MenuNav_Back_K2Node_InputActionEvent_31
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_MenuNav_Back_K2Node_InputActionEvent_31(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_MenuNav_Back_K2Node_InputActionEvent_31");

	Params::PAWN_PlayerGhost_C_InpActEvt_MenuNav_Back_K2Node_InputActionEvent_31 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.InpActEvt_AnyKey_K2Node_InputKeyEvent_2
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void APAWN_PlayerGhost_C::InpActEvt_AnyKey_K2Node_InputKeyEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "InpActEvt_AnyKey_K2Node_InputKeyEvent_2");

	Params::PAWN_PlayerGhost_C_InpActEvt_AnyKey_K2Node_InputKeyEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.EVENT_OnStartingLevelFinishedLoading
// (Private, BlueprintCallable, BlueprintEvent)

void APAWN_PlayerGhost_C::EVENT_OnStartingLevelFinishedLoading()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "EVENT_OnStartingLevelFinishedLoading");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavUp
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavUp(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavUp");

	Params::PAWN_PlayerGhost_C_HandleMenuNavUp Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavDown
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavDown(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavDown");

	Params::PAWN_PlayerGhost_C_HandleMenuNavDown Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavLeft
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavLeft(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavLeft");

	Params::PAWN_PlayerGhost_C_HandleMenuNavLeft Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavRight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavRight(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavRight");

	Params::PAWN_PlayerGhost_C_HandleMenuNavRight Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavAccept
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavAccept(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavAccept");

	Params::PAWN_PlayerGhost_C_HandleMenuNavAccept Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavBack
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavBack(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavBack");

	Params::PAWN_PlayerGhost_C_HandleMenuNavBack Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavAlt1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavAlt1(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavAlt1");

	Params::PAWN_PlayerGhost_C_HandleMenuNavAlt1 Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavAlt2
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavAlt2(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavAlt2");

	Params::PAWN_PlayerGhost_C_HandleMenuNavAlt2 Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavTabLeft
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavTabLeft(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavTabLeft");

	Params::PAWN_PlayerGhost_C_HandleMenuNavTabLeft Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleMenuNavTabRight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleMenuNavTabRight(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleMenuNavTabRight");

	Params::PAWN_PlayerGhost_C_HandleMenuNavTabRight Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleSecretCodeA
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleSecretCodeA(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleSecretCodeA");

	Params::PAWN_PlayerGhost_C_HandleSecretCodeA Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleSecretCodeB
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleSecretCodeB(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleSecretCodeB");

	Params::PAWN_PlayerGhost_C_HandleSecretCodeB Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PAWN_PlayerGhost.PAWN_PlayerGhost_C.HandleSecretCodeStart
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonDown                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void APAWN_PlayerGhost_C::HandleSecretCodeStart(bool ButtonDown)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PAWN_PlayerGhost_C", "HandleSecretCodeStart");

	Params::PAWN_PlayerGhost_C_HandleSecretCodeStart Parms{};

	Parms.ButtonDown = ButtonDown;

	UObject::ProcessEvent(Func, &Parms);
}

}

