#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SHAKE_DroneWobble

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SHAKE_DroneWobble.SHAKE_DroneWobble_C
// 0x0000 (0x01B0 - 0x01B0)
class USHAKE_DroneWobble_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SHAKE_DroneWobble_C">();
	}
	static class USHAKE_DroneWobble_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USHAKE_DroneWobble_C>();
	}
};
static_assert(alignof(USHAKE_DroneWobble_C) == 0x000010, "Wrong alignment on USHAKE_DroneWobble_C");
static_assert(sizeof(USHAKE_DroneWobble_C) == 0x0001B0, "Wrong size on USHAKE_DroneWobble_C");

}

