#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sign_Parent

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Sign_Parent.Sign_Parent_C.UserConstructionScript
// 0x0030 (0x0030 - 0x0000)
struct Sign_Parent_C_UserConstructionScript final
{
public:
	struct FVector4                               NewLocalVar_0;                                     // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_LinearColorToVector_ReturnValue;     // 0x0010(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_LinearColorToVector_ReturnValue_1;   // 0x001C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Sign_Parent_C_UserConstructionScript) == 0x000010, "Wrong alignment on Sign_Parent_C_UserConstructionScript");
static_assert(sizeof(Sign_Parent_C_UserConstructionScript) == 0x000030, "Wrong size on Sign_Parent_C_UserConstructionScript");
static_assert(offsetof(Sign_Parent_C_UserConstructionScript, NewLocalVar_0) == 0x000000, "Member 'Sign_Parent_C_UserConstructionScript::NewLocalVar_0' has a wrong offset!");
static_assert(offsetof(Sign_Parent_C_UserConstructionScript, CallFunc_Conv_LinearColorToVector_ReturnValue) == 0x000010, "Member 'Sign_Parent_C_UserConstructionScript::CallFunc_Conv_LinearColorToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Sign_Parent_C_UserConstructionScript, CallFunc_Conv_LinearColorToVector_ReturnValue_1) == 0x00001C, "Member 'Sign_Parent_C_UserConstructionScript::CallFunc_Conv_LinearColorToVector_ReturnValue_1' has a wrong offset!");

// Function Sign_Parent.Sign_Parent_C.ExecuteUbergraph_Sign_Parent
// 0x0004 (0x0004 - 0x0000)
struct Sign_Parent_C_ExecuteUbergraph_Sign_Parent final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Sign_Parent_C_ExecuteUbergraph_Sign_Parent) == 0x000004, "Wrong alignment on Sign_Parent_C_ExecuteUbergraph_Sign_Parent");
static_assert(sizeof(Sign_Parent_C_ExecuteUbergraph_Sign_Parent) == 0x000004, "Wrong size on Sign_Parent_C_ExecuteUbergraph_Sign_Parent");
static_assert(offsetof(Sign_Parent_C_ExecuteUbergraph_Sign_Parent, EntryPoint) == 0x000000, "Member 'Sign_Parent_C_ExecuteUbergraph_Sign_Parent::EntryPoint' has a wrong offset!");

}

