#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SKILL_CyborgElite_PlasmaCannon

#include "Basic.hpp"

#include "SKILL_ShootBullet_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SKILL_CyborgElite_PlasmaCannon.SKILL_CyborgElite_PlasmaCannon_C
// 0x0000 (0x00D8 - 0x00D8)
class USKILL_CyborgElite_PlasmaCannon_C : public USKILL_ShootBullet_C
{
public:
	void CanUseSkill(bool* Result);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SKILL_CyborgElite_PlasmaCannon_C">();
	}
	static class USKILL_CyborgElite_PlasmaCannon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USKILL_CyborgElite_PlasmaCannon_C>();
	}
};
static_assert(alignof(USKILL_CyborgElite_PlasmaCannon_C) == 0x000008, "Wrong alignment on USKILL_CyborgElite_PlasmaCannon_C");
static_assert(sizeof(USKILL_CyborgElite_PlasmaCannon_C) == 0x0000D8, "Wrong size on USKILL_CyborgElite_PlasmaCannon_C");

}

