#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STRUCT_ReferencedLootTable

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct STRUCT_ReferencedLootTable.STRUCT_ReferencedLootTable
// 0x0010 (0x0010 - 0x0000)
struct FSTRUCT_ReferencedLootTable final
{
public:
	class UDataTable*                             DataTable_2_9B43C7404009E3F571B132B5B29CF397;      // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SelectionCount_6_2FC2382344BA0AA7D672A2B34316FEE7; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FSTRUCT_ReferencedLootTable) == 0x000008, "Wrong alignment on FSTRUCT_ReferencedLootTable");
static_assert(sizeof(FSTRUCT_ReferencedLootTable) == 0x000010, "Wrong size on FSTRUCT_ReferencedLootTable");
static_assert(offsetof(FSTRUCT_ReferencedLootTable, DataTable_2_9B43C7404009E3F571B132B5B29CF397) == 0x000000, "Member 'FSTRUCT_ReferencedLootTable::DataTable_2_9B43C7404009E3F571B132B5B29CF397' has a wrong offset!");
static_assert(offsetof(FSTRUCT_ReferencedLootTable, SelectionCount_6_2FC2382344BA0AA7D672A2B34316FEE7) == 0x000008, "Member 'FSTRUCT_ReferencedLootTable::SelectionCount_6_2FC2382344BA0AA7D672A2B34316FEE7' has a wrong offset!");

}

