#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TASK_DisableHeadlook

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TASK_DisableHeadlook.TASK_DisableHeadlook_C
// 0x0008 (0x00B0 - 0x00A8)
class UTASK_DisableHeadlook_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_TASK_DisableHeadlook(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TASK_DisableHeadlook_C">();
	}
	static class UTASK_DisableHeadlook_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTASK_DisableHeadlook_C>();
	}
};
static_assert(alignof(UTASK_DisableHeadlook_C) == 0x000008, "Wrong alignment on UTASK_DisableHeadlook_C");
static_assert(sizeof(UTASK_DisableHeadlook_C) == 0x0000B0, "Wrong size on UTASK_DisableHeadlook_C");
static_assert(offsetof(UTASK_DisableHeadlook_C, UberGraphFrame) == 0x0000A8, "Member 'UTASK_DisableHeadlook_C::UberGraphFrame' has a wrong offset!");

}

