#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TRIGGER_MusicVolume_Exploration

#include "Basic.hpp"

#include "TRIGGER_MusicVolume_Exploration_classes.hpp"
#include "TRIGGER_MusicVolume_Exploration_parameters.hpp"


namespace SDK
{

// Function TRIGGER_MusicVolume_Exploration.TRIGGER_MusicVolume_Exploration_C.OnEnterVolume
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGI_SinglePlayer_C*               GameInstance                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UGI_SinglePlayer_C*               OutGameInstance                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATRIGGER_MusicVolume_Exploration_C::OnEnterVolume(class UGI_SinglePlayer_C* GameInstance, class UGI_SinglePlayer_C** OutGameInstance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TRIGGER_MusicVolume_Exploration_C", "OnEnterVolume");

	Params::TRIGGER_MusicVolume_Exploration_C_OnEnterVolume Parms{};

	Parms.GameInstance = GameInstance;

	UObject::ProcessEvent(Func, &Parms);

	if (OutGameInstance != nullptr)
		*OutGameInstance = Parms.OutGameInstance;
}

}

