#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WIDGET_SubMenu_Tab

#include "Basic.hpp"

#include "WIDGET_SubMenu_Tab_classes.hpp"
#include "WIDGET_SubMenu_Tab_parameters.hpp"


namespace SDK
{

// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.TabClicked__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWIDGET_SubMenu_Tab_C::TabClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "TabClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.ExecuteUbergraph_WIDGET_SubMenu_Tab
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWIDGET_SubMenu_Tab_C::ExecuteUbergraph_WIDGET_SubMenu_Tab(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "ExecuteUbergraph_WIDGET_SubMenu_Tab");

	Params::WIDGET_SubMenu_Tab_C_ExecuteUbergraph_WIDGET_SubMenu_Tab Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWIDGET_SubMenu_Tab_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "PreConstruct");

	Params::WIDGET_SubMenu_Tab_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.EVENT_OnClicked
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWIDGET_SubMenu_Tab_C::EVENT_OnClicked(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "EVENT_OnClicked");

	Params::WIDGET_SubMenu_Tab_C_EVENT_OnClicked Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.SetIsSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWIDGET_SubMenu_Tab_C::SetIsSelected(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "SetIsSelected");

	Params::WIDGET_SubMenu_Tab_C_SetIsSelected Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.SetIsHighlighted
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWIDGET_SubMenu_Tab_C::SetIsHighlighted(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "SetIsHighlighted");

	Params::WIDGET_SubMenu_Tab_C_SetIsHighlighted Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.EVENT_OnMouseEnter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWIDGET_SubMenu_Tab_C::EVENT_OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "EVENT_OnMouseEnter");

	Params::WIDGET_SubMenu_Tab_C_EVENT_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.EVENT_OnMouseExit
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWIDGET_SubMenu_Tab_C::EVENT_OnMouseExit(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "EVENT_OnMouseExit");

	Params::WIDGET_SubMenu_Tab_C_EVENT_OnMouseExit Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_SubMenu_Tab.WIDGET_SubMenu_Tab_C.SetPlatformIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UWIDGET_SubMenu_Tab_C::SetPlatformIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_SubMenu_Tab_C", "SetPlatformIcon");

	UObject::ProcessEvent(Func, nullptr);
}

}

