#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WIDGET_DifficultyCategoryPanel

#include "Basic.hpp"

#include "WIDGET_DifficultyCategoryPanel_classes.hpp"
#include "WIDGET_DifficultyCategoryPanel_parameters.hpp"


namespace SDK
{

// Function WIDGET_DifficultyCategoryPanel.WIDGET_DifficultyCategoryPanel_C.ExpandContainer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Highlighted_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWIDGET_DifficultyCategoryPanel_C::ExpandContainer(bool Highlighted_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_DifficultyCategoryPanel_C", "ExpandContainer");

	Params::WIDGET_DifficultyCategoryPanel_C_ExpandContainer Parms{};

	Parms.Highlighted_0 = Highlighted_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_DifficultyCategoryPanel.WIDGET_DifficultyCategoryPanel_C.ShrinkContainer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Highlighted_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWIDGET_DifficultyCategoryPanel_C::ShrinkContainer(bool Highlighted_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_DifficultyCategoryPanel_C", "ShrinkContainer");

	Params::WIDGET_DifficultyCategoryPanel_C_ShrinkContainer Parms{};

	Parms.Highlighted_0 = Highlighted_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

