#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WIDGET_MouseOverDetails

#include "Basic.hpp"

#include "WIDGET_MouseOverDetails_classes.hpp"
#include "WIDGET_MouseOverDetails_parameters.hpp"


namespace SDK
{

// Function WIDGET_MouseOverDetails.WIDGET_MouseOverDetails_C.ExecuteUbergraph_WIDGET_MouseOverDetails
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWIDGET_MouseOverDetails_C::ExecuteUbergraph_WIDGET_MouseOverDetails(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_MouseOverDetails_C", "ExecuteUbergraph_WIDGET_MouseOverDetails");

	Params::WIDGET_MouseOverDetails_C_ExecuteUbergraph_WIDGET_MouseOverDetails Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_MouseOverDetails.WIDGET_MouseOverDetails_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWIDGET_MouseOverDetails_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_MouseOverDetails_C", "PreConstruct");

	Params::WIDGET_MouseOverDetails_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WIDGET_MouseOverDetails.WIDGET_MouseOverDetails_C.SetMouseOverText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWIDGET_MouseOverDetails_C::SetMouseOverText(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WIDGET_MouseOverDetails_C", "SetMouseOverText");

	Params::WIDGET_MouseOverDetails_C_SetMouseOverText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}

}

