#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WIDGET_OptionsMenu_Audio

#include "Basic.hpp"


namespace SDK::Params
{

// Function WIDGET_OptionsMenu_Audio.WIDGET_OptionsMenu_Audio_C.InitializeMenu
// 0x0008 (0x0008 - 0x0000)
struct WIDGET_OptionsMenu_Audio_C_InitializeMenu final
{
public:
	class UWIDGET_MenuBase_C*                     ParentMenuWidget;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WIDGET_OptionsMenu_Audio_C_InitializeMenu) == 0x000008, "Wrong alignment on WIDGET_OptionsMenu_Audio_C_InitializeMenu");
static_assert(sizeof(WIDGET_OptionsMenu_Audio_C_InitializeMenu) == 0x000008, "Wrong size on WIDGET_OptionsMenu_Audio_C_InitializeMenu");
static_assert(offsetof(WIDGET_OptionsMenu_Audio_C_InitializeMenu, ParentMenuWidget) == 0x000000, "Member 'WIDGET_OptionsMenu_Audio_C_InitializeMenu::ParentMenuWidget' has a wrong offset!");

}

