#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WIREPUZZLE_Simple

#include "Basic.hpp"

#include "WIREPUZZLE_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WIREPUZZLE_Simple.WIREPUZZLE_Simple_C
// 0x0000 (0x07D8 - 0x07D8)
class AWIREPUZZLE_Simple_C final : public AWIREPUZZLE_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WIREPUZZLE_Simple_C">();
	}
	static class AWIREPUZZLE_Simple_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWIREPUZZLE_Simple_C>();
	}
};
static_assert(alignof(AWIREPUZZLE_Simple_C) == 0x000008, "Wrong alignment on AWIREPUZZLE_Simple_C");
static_assert(sizeof(AWIREPUZZLE_Simple_C) == 0x0007D8, "Wrong size on AWIREPUZZLE_Simple_C");

}

