#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero1_CityFlythrough

#include "Basic.hpp"

#include "ENUM_HackerGender_structs.hpp"


namespace SDK::Params
{

// Function 01_CityFlythrough.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_6
// 0x0008 (0x0008 - 0x0000)
struct SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_6 final
{
public:
	class ASkeletalMeshActor*                     anim_cine_intro_sc_01_Hacker_LookOutWindow;        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_6) == 0x000008, "Wrong alignment on SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_6");
static_assert(sizeof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_6) == 0x000008, "Wrong size on SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_6");
static_assert(offsetof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_6, anim_cine_intro_sc_01_Hacker_LookOutWindow) == 0x000000, "Member 'SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_6::anim_cine_intro_sc_01_Hacker_LookOutWindow' has a wrong offset!");

// Function 01_CityFlythrough.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_1
// 0x0008 (0x0008 - 0x0000)
struct SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1 final
{
public:
	class ABP_IntroDrone_C*                       BP_IntroDrone;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1) == 0x000008, "Wrong alignment on SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1");
static_assert(sizeof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1) == 0x000008, "Wrong size on SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1");
static_assert(offsetof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1, BP_IntroDrone) == 0x000000, "Member 'SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_1::BP_IntroDrone' has a wrong offset!");

// Function 01_CityFlythrough.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// 0x0008 (0x0008 - 0x0000)
struct SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0 final
{
public:
	class ABP_IntroDrone_C*                       BP_IntroDrone;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0) == 0x000008, "Wrong alignment on SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0");
static_assert(sizeof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0) == 0x000008, "Wrong size on SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0");
static_assert(offsetof(SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0, BP_IntroDrone) == 0x000000, "Member 'SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0::BP_IntroDrone' has a wrong offset!");

// Function 01_CityFlythrough.SequenceDirector_C.BP_IntroDrone_TickHUD
// 0x0008 (0x0008 - 0x0000)
struct SequenceDirector_C_BP_IntroDrone_TickHUD final
{
public:
	class ABP_IntroDrone_C*                       BP_IntroDrone;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SequenceDirector_C_BP_IntroDrone_TickHUD) == 0x000008, "Wrong alignment on SequenceDirector_C_BP_IntroDrone_TickHUD");
static_assert(sizeof(SequenceDirector_C_BP_IntroDrone_TickHUD) == 0x000008, "Wrong size on SequenceDirector_C_BP_IntroDrone_TickHUD");
static_assert(offsetof(SequenceDirector_C_BP_IntroDrone_TickHUD, BP_IntroDrone) == 0x000000, "Member 'SequenceDirector_C_BP_IntroDrone_TickHUD::BP_IntroDrone' has a wrong offset!");

// Function 01_CityFlythrough.SequenceDirector_C.BP_IntroDrone_Setup
// 0x0008 (0x0008 - 0x0000)
struct SequenceDirector_C_BP_IntroDrone_Setup final
{
public:
	class ABP_IntroDrone_C*                       BP_IntroDrone;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SequenceDirector_C_BP_IntroDrone_Setup) == 0x000008, "Wrong alignment on SequenceDirector_C_BP_IntroDrone_Setup");
static_assert(sizeof(SequenceDirector_C_BP_IntroDrone_Setup) == 0x000008, "Wrong size on SequenceDirector_C_BP_IntroDrone_Setup");
static_assert(offsetof(SequenceDirector_C_BP_IntroDrone_Setup, BP_IntroDrone) == 0x000000, "Member 'SequenceDirector_C_BP_IntroDrone_Setup::BP_IntroDrone' has a wrong offset!");

// Function 01_CityFlythrough.SequenceDirector_C.anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0
// 0x0008 (0x0008 - 0x0000)
struct SequenceDirector_C_anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0 final
{
public:
	class ASkeletalMeshActor*                     anim_cine_intro_sc_01_Hacker_LookOutWindow;        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SequenceDirector_C_anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0) == 0x000008, "Wrong alignment on SequenceDirector_C_anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0");
static_assert(sizeof(SequenceDirector_C_anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0) == 0x000008, "Wrong size on SequenceDirector_C_anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0");
static_assert(offsetof(SequenceDirector_C_anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0, anim_cine_intro_sc_01_Hacker_LookOutWindow) == 0x000000, "Member 'SequenceDirector_C_anim_cine_intro_sc_01_Hacker_LookOutWindow_Event_0::anim_cine_intro_sc_01_Hacker_LookOutWindow' has a wrong offset!");

// Function 01_CityFlythrough.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// 0x0050 (0x0050 - 0x0000)
struct SequenceDirector_C_ExecuteUbergraph_SequenceDirector final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_IntroDrone_C*                       CallFunc_GetActorOfClass_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASkeletalMeshActor*                     K2Node_CustomEvent_anim_cine_intro_sc_01_Hacker_LookOutWindow; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGI_SinglePlayer_C*                     K2Node_DynamicCast_AsGI_Single_Player;             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_IntroDrone_C*                       K2Node_CustomEvent_BP_IntroDrone;                  // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ENUM_HackerGender                             CallFunc_GetHackerGender_Result;                   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_IntroDrone_C*                       K2Node_CustomEvent_BP_IntroDrone_1;                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector) == 0x000008, "Wrong alignment on SequenceDirector_C_ExecuteUbergraph_SequenceDirector");
static_assert(sizeof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector) == 0x000050, "Wrong size on SequenceDirector_C_ExecuteUbergraph_SequenceDirector");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, EntryPoint) == 0x000000, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::EntryPoint' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, CallFunc_GetActorOfClass_ReturnValue) == 0x000008, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::CallFunc_GetActorOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, K2Node_CustomEvent_anim_cine_intro_sc_01_Hacker_LookOutWindow) == 0x000018, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::K2Node_CustomEvent_anim_cine_intro_sc_01_Hacker_LookOutWindow' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, CallFunc_GetGameInstance_ReturnValue) == 0x000020, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, K2Node_DynamicCast_AsGI_Single_Player) == 0x000028, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::K2Node_DynamicCast_AsGI_Single_Player' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, K2Node_CustomEvent_BP_IntroDrone) == 0x000038, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::K2Node_CustomEvent_BP_IntroDrone' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, CallFunc_GetHackerGender_Result) == 0x000040, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::CallFunc_GetHackerGender_Result' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, K2Node_SwitchEnum_CmpSuccess) == 0x000041, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(SequenceDirector_C_ExecuteUbergraph_SequenceDirector, K2Node_CustomEvent_BP_IntroDrone_1) == 0x000048, "Member 'SequenceDirector_C_ExecuteUbergraph_SequenceDirector::K2Node_CustomEvent_BP_IntroDrone_1' has a wrong offset!");

}

