#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero0_Menu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 00_Menu.00_Menu_C
// 0x0008 (0x0230 - 0x0228)
class AZero0_Menu_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_00_Menu(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"00_Menu_C">();
	}
	static class AZero0_Menu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AZero0_Menu_C>();
	}
};
static_assert(alignof(AZero0_Menu_C) == 0x000008, "Wrong alignment on AZero0_Menu_C");
static_assert(sizeof(AZero0_Menu_C) == 0x000230, "Wrong size on AZero0_Menu_C");
static_assert(offsetof(AZero0_Menu_C, UberGraphFrame) == 0x000228, "Member 'AZero0_Menu_C::UberGraphFrame' has a wrong offset!");

}

