#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero1_CityFlythrough_Start

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 01_CityFlythrough_Start.SequenceDirector_C
// 0x0018 (0x0050 - 0x0038)
class Zero1_CityFlythrough_Start::USequenceDirector_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_IntroDrone_C*                       BP_Intro_Drone;                                    // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       Widget;                                            // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SequenceEvent__ENTRYPOINTSequenceDirector_1(class ABP_IntroDrone_C* BP_IntroDrone);
	void SequenceEvent__ENTRYPOINTSequenceDirector_0(class ABP_IntroDrone_C* BP_IntroDrone);
	void BP_IntroDrone_Setup(class ABP_IntroDrone_C* BP_IntroDrone);
	void BP_IntroDrone_TickHUD(class ABP_IntroDrone_C* BP_IntroDrone);
	void ExecuteUbergraph_SequenceDirector(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass 01_CityFlythrough_Start.SequenceDirector_C", true, "SequenceDirector_C">();
	}
	static class Zero1_CityFlythrough_Start::USequenceDirector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Zero1_CityFlythrough_Start::USequenceDirector_C>();
	}
};
static_assert(alignof(Zero1_CityFlythrough_Start::USequenceDirector_C) == 0x000008, "Wrong alignment on Zero1_CityFlythrough_Start::USequenceDirector_C");
static_assert(sizeof(Zero1_CityFlythrough_Start::USequenceDirector_C) == 0x000050, "Wrong size on Zero1_CityFlythrough_Start::USequenceDirector_C");
static_assert(offsetof(Zero1_CityFlythrough_Start::USequenceDirector_C, UberGraphFrame) == 0x000038, "Member 'Zero1_CityFlythrough_Start::USequenceDirector_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(Zero1_CityFlythrough_Start::USequenceDirector_C, BP_Intro_Drone) == 0x000040, "Member 'Zero1_CityFlythrough_Start::USequenceDirector_C::BP_Intro_Drone' has a wrong offset!");
static_assert(offsetof(Zero1_CityFlythrough_Start::USequenceDirector_C, Widget) == 0x000048, "Member 'Zero1_CityFlythrough_Start::USequenceDirector_C::Widget' has a wrong offset!");

}

